version: 0.0
os: linux
files: 
  - source: /
    destination: /var/www/html
#     overwrite: yes
# file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      runas: root